// Generated by CoffeeScript 1.11.1
(function() {
  var Twitter, config, favoriteTweet, rand, retweet, twit;

  twit = require('twit');

  config = require('./config.js');

  rand = function(arr) {
    var index;
    index = Math.floor(Math.random() * arr.length);
    return arr[index];
  };

  Twitter = new twit(config);

  retweet = function() {
    var params;
    params = {
      q: '#logistics, #shipping, #freight, #supplychain',
      result_type: 'mixed',
      lang: 'en'
    };
    return Twitter.get('search/tweets', params, function(err, data) {
      var retweetId;
      if (err === false) {
        retweetId = data.statuses[0].id_str;
        return Twitter.post('statuses/retweet/:id', {
          id: retweetId
        }, function(err, response) {
          if (response) {
            console.log('Retweeted!');
          }
          if (err) {
            console.log('Something went wrong while Retweeting.');
            return console.log(err);
          }
        });
      } else {
        return console.log('Something went wrong while Searching.');
      }
    });
  };

  favoriteTweet = function() {
    var params;
    params = {
      q: '#logistics, #shipping, #transport',
      result_type: 'mixed',
      lang: 'en'
    };
    return Twitter.get('search/tweets', params, function(err, data) {
      var randomTweet, tweet;
      tweet = data.statuses;
      randomTweet = rand(tweet);
      if (typeof randomTweet !== 'undefined') {
        return Twitter.post('favorites/create', {
          id: randomTweet.id_str
        }, function(err, response) {
          if (err) {
            return console.log('Something went wrong on Favorite Tweet.');
          } else {
            return console.log('Favorite OK.');
          }
        });
      }
    });
  };

  favoriteTweet();

  setInterval(favoriteTweet, 15 * 60 * 1000);

  retweet();

  setInterval(retweet, 15 * 60 * 1000);

}).call(this);
