// Generated by CoffeeScript 1.11.1
(function() {
  var DEFAULT_OPTIONS, DEFAULT_TIME, ONE_MINUTE, ONE_SECOND, Twitter, config, favoriteTweet, getAndSetConfig, options, queryList, rand, request, retweet, setCustomTimeout, twit;

  twit = require('twit');

  config = require('./config.js');

  request = require('request');

  ONE_SECOND = 1000;

  ONE_MINUTE = 60 * ONE_SECOND;

  DEFAULT_TIME = 5 * ONE_MINUTE;

  DEFAULT_OPTIONS = {
    "queryList": ["virtualreality", "#vr", "#oculus", "#vive", "revrsed", "psvr"],
    "frequencyInMinutes": 10
  };

  rand = function(arr) {
    var index;
    index = Math.floor(Math.random() * arr.length);
    return arr[index];
  };

  Twitter = new twit(config);

  queryList = DEFAULT_OPTIONS.queryList;

  retweet = function() {
    var params;
    params = {
      q: rand(queryList),
      result_type: 'mixed',
      lang: 'en'
    };
    return Twitter.get('search/tweets', params, function(err, data) {
      var randomTweet, retweetId, tweet;
      tweet = data.statuses;
      randomTweet = rand(tweet);
      if (err == null) {
        retweetId = randomTweet.id_str;
        return Twitter.post('statuses/retweet/:id', {
          id: retweetId
        }, function(err, response) {
          if ((response != null) && (err == null)) {
            console.log('Retweeted!');
          }
          if (err != null) {
            console.log('Something went wrong while Retweeting.');
            return console.log(err.message);
          }
        });
      } else {
        console.log('Something went wrong while Searching.');
        return console.log(err);
      }
    });
  };

  favoriteTweet = function() {
    var params;
    params = {
      q: rand(queryList),
      result_type: 'mixed',
      lang: 'en'
    };
    return Twitter.get('search/tweets', params, function(err, data) {
      var randomTweet, tweet;
      tweet = data.statuses;
      randomTweet = rand(tweet);
      if (typeof randomTweet !== 'undefined') {
        return Twitter.post('favorites/create', {
          id: randomTweet.id_str
        }, function(err, response) {
          if (err != null) {
            console.log('Something went wrong on Favorite Tweet.');
            return console.log(err.message);
          } else {
            return console.log('Favorite OK.');
          }
        });
      }
    });
  };

  setCustomTimeout = function(callback, time) {
    var internalCallback;
    internalCallback = (function(seconds) {
      return function() {
        setTimeout(internalCallback, config.frequencyInMinutes * ONE_MINUTE * ONE_SECOND);
        callback();
        if (config.frequencyInMinutes == null) {
          config.frequencyInMinutes = DEFAULT_OPTIONS.frequencyInMinutes;
        }
      };
    })();
    setTimeout(internalCallback, config.frequencyInMinutes);
  };

  options = {
    url: 'https://raw.githubusercontent.com/revrsed/bot/master/query.json',
    headers: {
      'Cache-Control': 'no-cache'
    }
  };

  getAndSetConfig = function() {
    return request.get(options, function(err, resp, body) {
      try {
        config = JSON.parse(body);
      } catch (error) {
        err = error;
        console.log('config sucks, using fallback');
        config = DEFAULT_OPTIONS;
      }
    });
  };

  config = {};

  setCustomTimeout(getAndSetConfig, ONE_SECOND, 0);

  retweet();

  favoriteTweet();

  setCustomTimeout(retweet, 5 * ONE_MINUTE);

  setCustomTimeout(favoriteTweet, 5 * ONE_MINUTE);

}).call(this);
